### ISSUE TITLE
Only chromosome 1 seems to be scanned

### ISSUE THREAD

**Issue by arundeep-singh-personalis** [ylab-hi/ScanITD#3]
Hi, I'm using a full BAM that has confirmed from pileup FLT3_ITD insertion reads in chromosome 13, but when I run ScanITD, I've only been seeing output in chromosome 1. Is there a mistake in the way I'm running it? Here is my command:
`python ScanITD.py --vaf 0.02 -i Samples/${1}.recal.bam -r hs37d5.fa -o $1_MVAF2%`

And here is the output:

> ##fileformat=VCFv4.1
##source=ScanITD 0.3
##ALT=<ID=TDUP,Description="Tandem duplication">
##ALT=<ID=INS,Description="Insertion">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=AO,Number=1,Type=Integer,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=AB,Number=1,Type=Float,Description="Estimated allele frequency in the range (0,1], representing the ratio of reads showing the alternative allele to all reads">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="The type of event, INS and TDUP.">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=CHR2,Number=1,Type=String,Description="Chromosome for END coordinate in case of a translocation">
##INFO=<ID=END,Number=1,Type=Integer,Description="nd position of the structural variant">
##INFO=<ID=SVMETHOD,Number=1,Type=String,Description="Type of approach used to detect SV">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TEST_ITD_BAM_MVAF2%
1	884070	.	.	<TDUP>	.	.	NS=1;AO=113;DP=348;AB=0.32;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	884070	.	.	<TDUP>	.	.	NS=1;AO=114;DP=348;AB=0.33;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	884070	.	.	<TDUP>	.	.	NS=1;AO=112;DP=348;AB=0.32;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	884070	.	.	<TDUP>	.	.	NS=1;AO=117;DP=348;AB=0.34;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	884070	.	.	<TDUP>	.	.	NS=1;AO=115;DP=348;AB=0.33;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	884070	.	.	<TDUP>	.	.	NS=1;AO=198;DP=348;AB=0.57;SVLEN=41;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=884110	GT	0/1
1	931634	.	.	<TDUP>	.	.	NS=1;AO=5;DP=16;AB=0.31;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=931643	GT	0/1
1	1229157	.	.	<TDUP>	.	.	NS=1;AO=7;DP=199;AB=0.035;SVLEN=20;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=1229176	GT	0/1
1	1229112	.	.	<TDUP>	.	.	NS=1;AO=22;DP=109;AB=0.2;SVLEN=20;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=1229131	GT	0/1
1	1886493	.	.	<TDUP>	.	.	NS=1;AO=5;DP=45;AB=0.11;SVLEN=36;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=1886528	GT	0/1
1	1886475	.	.	<TDUP>	.	.	NS=1;AO=4;DP=45;AB=0.089;SVLEN=54;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=1886528	GT	0/1
1	2002490	.	.	<TDUP>	.	.	NS=1;AO=4;DP=21;AB=0.19;SVLEN=13;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=2002502	GT	0/1
1	2332691	.	.	<TDUP>	.	.	NS=1;AO=5;DP=28;AB=0.18;SVLEN=13;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=2332703	GT	0/1
1	3643465	.	.	<TDUP>	.	.	NS=1;AO=18;DP=22;AB=0.82;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=3643476	GT	0/1
1	3789178	.	.	<TDUP>	.	.	NS=1;AO=58;DP=213;AB=0.27;SVLEN=17;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=3789194	GT	0/1
1	3789215	.	.	<TDUP>	.	.	NS=1;AO=12;DP=108;AB=0.11;SVLEN=17;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=3789231	GT	0/1
1	3844055	.	.	<TDUP>	.	.	NS=1;AO=4;DP=12;AB=0.33;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=3844066	GT	0/1
1	7917185	.	.	<TDUP>	.	.	NS=1;AO=4;DP=18;AB=0.22;SVLEN=20;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=7917204	GT	0/1
1	7917185	.	.	<TDUP>	.	.	NS=1;AO=5;DP=18;AB=0.28;SVLEN=20;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=7917204	GT	0/1
1	9258982	.	.	<TDUP>	.	.	NS=1;AO=8;DP=19;AB=0.42;SVLEN=16;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=9258997	GT	0/1
1	9283824	.	.	<TDUP>	.	.	NS=1;AO=5;DP=24;AB=0.21;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=9283835	GT	0/1
1	10615699	.	.	<TDUP>	.	.	NS=1;AO=17;DP=68;AB=0.25;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=10615708	GT	0/1
1	10615715	.	.	<TDUP>	.	.	NS=1;AO=4;DP=75;AB=0.053;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=10615724	GT	0/1
1	10955767	.	.	<TDUP>	.	.	NS=1;AO=5;DP=19;AB=0.26;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=10955778	GT	0/1
1	11582917	.	.	<TDUP>	.	.	NS=1;AO=8;DP=342;AB=0.023;SVLEN=11;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=11582927	GT	0/1
1	11583004	.	.	<TDUP>	.	.	NS=1;AO=8;DP=161;AB=0.05;SVLEN=22;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=11583025	GT	0/1
1	11593787	.	.	<TDUP>	.	.	NS=1;AO=6;DP=141;AB=0.043;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=11593796	GT	0/1
1	11593793	.	.	<TDUP>	.	.	NS=1;AO=66;DP=141;AB=0.47;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=11593804	GT	0/1
1	12004479	.	.	<TDUP>	.	.	NS=1;AO=16;DP=89;AB=0.18;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=12004488	GT	0/1
1	12004480	.	.	<TDUP>	.	.	NS=1;AO=9;DP=95;AB=0.095;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=12004489	GT	0/1
1	13132898	.	.	<TDUP>	.	.	NS=1;AO=5;DP=10;AB=0.5;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=13132907	GT	0/1
1	16370860	.	.	<TDUP>	.	.	NS=1;AO=30;DP=38;AB=0.79;SVLEN=14;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16370873	GT	0/1
1	16370858	.	.	<TDUP>	.	.	NS=1;AO=4;DP=38;AB=0.11;SVLEN=16;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16370873	GT	0/1
1	16370862	.	.	<TDUP>	.	.	NS=1;AO=5;DP=38;AB=0.13;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16370873	GT	0/1
1	16376519	.	.	<TDUP>	.	.	NS=1;AO=17;DP=27;AB=0.63;SVLEN=9820;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16386338	GT	0/1
1	16894034	.	.	<TDUP>	.	.	NS=1;AO=4;DP=85;AB=0.047;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16894045	GT	0/1
1	16959732	.	.	<TDUP>	.	.	NS=1;AO=79;DP=324;AB=0.24;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=16959743	GT	0/1
1	17027900	.	.	<TDUP>	.	.	NS=1;AO=11;DP=29;AB=0.38;SVLEN=38;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=17027937	GT	0/1
1	17796017	.	.	<TDUP>	.	.	NS=1;AO=9;DP=10;AB=0.9;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=17796028	GT	0/1
1	18792550	.	.	<TDUP>	.	.	NS=1;AO=6;DP=17;AB=0.35;SVLEN=59;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=18792608	GT	0/1
1	19071191	.	.	<TDUP>	.	.	NS=1;AO=22;DP=81;AB=0.27;SVLEN=16;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=19071206	GT	0/1
1	19071166	.	.	<TDUP>	.	.	NS=1;AO=4;DP=58;AB=0.069;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=19071177	GT	0/1
1	19203155	.	.	<TDUP>	.	.	NS=1;AO=4;DP=89;AB=0.045;SVLEN=22;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=19203176	GT	0/1
1	19203132	.	.	<TDUP>	.	.	NS=1;AO=4;DP=156;AB=0.026;SVLEN=24;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=19203155	GT	0/1
1	19798061	.	.	<TDUP>	.	.	NS=1;AO=5;DP=17;AB=0.29;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=19798070	GT	0/1
1	20617658	.	.	<TDUP>	.	.	NS=1;AO=23;DP=96;AB=0.24;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=20617667	GT	0/1
1	23955189	.	.	<TDUP>	.	.	NS=1;AO=15;DP=35;AB=0.43;SVLEN=24;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=23955212	GT	0/1
1	24195734	.	.	<TDUP>	.	.	NS=1;AO=5;DP=20;AB=0.25;SVLEN=11;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=24195744	GT	0/1
1	24545759	.	.	<TDUP>	.	.	NS=1;AO=5;DP=23;AB=0.22;SVLEN=12;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=24545770	GT	0/1
1	27623298	.	.	<TDUP>	.	.	NS=1;AO=11;DP=53;AB=0.21;SVLEN=18;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=27623315	GT	0/1
1	27623265	.	.	<TDUP>	.	.	NS=1;AO=4;DP=25;AB=0.16;SVLEN=18;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=27623282	GT	0/1
1	30953847	.	.	<TDUP>	.	.	NS=1;AO=7;DP=32;AB=0.22;SVLEN=10;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=30953856	GT	0/1
1	30953837	.	.	<TDUP>	.	.	NS=1;AO=5;DP=32;AB=0.16;SVLEN=20;SVTYPE=TDUP;SVMETHOD=ScanITD_ALN;CHR2=1;END=30953856	GT	0/1

Thank you very much for your help.

**Comment by dolittle007** [comment]
Can you check the chromosome names in your input BAM file (${1}.recal.bam)?
ScanITD will analyze all the chromosomes in the BAM file.
