### ISSUE TITLE
Empty VCF

### ISSUE THREAD

**Issue by itslittman** [ylab-hi/ScanITD#7]
I ran scanITD and no errors were thrown, but the VCF output shows no variants (it has the headers and everything - scanITD just didn’t seem to find anything. The issue is that the sample has tons of ITDs - I’m looking at them right now in IGV clear as day.

**Comment by dolittle007** [comment]
Hi, first of all, could you test the test data using the corresponding dependents (https://github.com/ylab-hi/ScanITD/tree/master/Test)?

**Comment by itslittman** [comment]
@dolittle007 it doesn't appear that the test worked although it threw no errors. I should also mention, my own data is Nanopore direct-RNA data, not short-read.

Edit: The test worked when I just tried it on our HPC/Linux environment, but not with newer python etc. on my Mac. Not sure why that would be -- I get certain things like TensorFlow can be version-sensitive but if it's a version issue on my Mac, not sure what would cause the empty VCF.

**Comment by itslittman** [comment]
@dolittle007 Trying my own input in the new environment, I get: 

pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort_core] truncated file. Aborting.\n'

Would I be wrong to guess that the script doesn't like Minimap2's CIGAR format or something?

**Comment by dolittle007** [comment]
@itslittman ScanITD is currently designed for Illumina WES data, not long-reads data or RNA-seq data. But thanks to your suggestion, I am thinking of making it work with long-read data.
